USE [CookBookDB]

INSERT INTO Category(Name, ParentId) VALUES ('Закуски', null)
INSERT INTO Category(Name, ParentId) VALUES ('Горячие закуски', 1)
INSERT INTO Category(Name, ParentId) VALUES ('Холодные закуски', 1)
INSERT INTO Category(Name, ParentId) VALUES ('Основные блюда', null)
INSERT INTO Category(Name, ParentId) VALUES ('Пицца', null)
INSERT INTO Category(Name, ParentId) VALUES ('Паста', null)
INSERT INTO Category(Name, ParentId) VALUES ('Салаты', null)
INSERT INTO Category(Name, ParentId) VALUES ('Супы', null)
INSERT INTO Category(Name, ParentId) VALUES ('Горячие супы', 8)
INSERT INTO Category(Name, ParentId) VALUES ('Холодные супы', 8)
INSERT INTO Category(Name, ParentId) VALUES ('Гарниры', null)
INSERT INTO Category(Name, ParentId) VALUES ('Суши', null)
INSERT INTO Category(Name, ParentId) VALUES ('Бургеры', null)
INSERT INTO Category(Name, ParentId) VALUES ('Отбивные', 4)
INSERT INTO Category(Name, ParentId) VALUES ('Котлеты', 4)

INSERT INTO Ingridient(Name) VALUES ('Вода')
INSERT INTO Ingridient(Name) VALUES ('Соль')
INSERT INTO Ingridient(Name) VALUES ('Молотый перец')
INSERT INTO Ingridient(Name) VALUES ('Лавровый лист')
INSERT INTO Ingridient(Name) VALUES ('Укроп')
INSERT INTO Ingridient(Name) VALUES ('Петрушка')
INSERT INTO Ingridient(Name) VALUES ('Картофель')
INSERT INTO Ingridient(Name) VALUES ('Морковь')
INSERT INTO Ingridient(Name) VALUES ('Свекла')
INSERT INTO Ingridient(Name) VALUES ('Капуста')
INSERT INTO Ingridient(Name) VALUES ('Лук')
INSERT INTO Ingridient(Name) VALUES ('Томатная паста')
INSERT INTO Ingridient(Name) VALUES ('Растительное масло')
INSERT INTO Ingridient(Name) VALUES ('Чеснок')
INSERT INTO Ingridient(Name) VALUES ('Яйцо')
INSERT INTO Ingridient(Name) VALUES ('Огурец')
INSERT INTO Ingridient(Name) VALUES ('Помидор')
INSERT INTO Ingridient(Name) VALUES ('Болгарский перец')
INSERT INTO Ingridient(Name) VALUES ('Филе куриное')
INSERT INTO Ingridient(Name) VALUES ('Говядина')
INSERT INTO Ingridient(Name) VALUES ('Свинина')
INSERT INTO Ingridient(Name) VALUES ('Фарш свиной')
INSERT INTO Ingridient(Name) VALUES ('Сыр Фета')
INSERT INTO Ingridient(Name) VALUES ('Фарш говяжий')
INSERT INTO Ingridient(Name) VALUES ('Белый хлеб')
INSERT INTO Ingridient(Name) VALUES ('Молоко')
INSERT INTO Ingridient(Name) VALUES ('Оливковое масло')

INSERT INTO Recipe(Name,ImageUrl,CategoryId) VALUES ('Борщ','E:\Images\Борщ.jpg',9) 
INSERT INTO Recipe(Name,ImageUrl,CategoryId) VALUES ('Греческий салат','E:\Images\ГреческийСалат.jpg',7) 
INSERT INTO Recipe(Name,ImageUrl,CategoryId) VALUES ('Котлеты из свинины-говядины','E:\Images\Котлеты.jpg',15) 
INSERT INTO Recipe(Name,ImageUrl,CategoryId) VALUES ('Поджаренное куриное филе','E:\Images\КуриноеФиле.jpg',14) 
INSERT INTO Recipe(Name,ImageUrl,CategoryId) VALUES ('Салат из огурцов и помидоров','E:\Images\СалатОгурецПомидор.jpg',7) 
INSERT INTO Recipe(Name,ImageUrl,CategoryId) VALUES ('Отбивные из свинины','E:\Images\СвиныеОтбивные.jpg',14) 
INSERT INTO Recipe(Name,ImageUrl,CategoryId) VALUES ('Щи','E:\Images\Щи.jpg',9) 
INSERT INTO Recipe(Name,ImageUrl,CategoryId) VALUES ('Овощная нарезка',null,3)

INSERT INTO RecipeDetails(RecipeId,CookingTime,CookingTemperature,Description,Sequencing) VALUES (1,'2-2.5 часа','100 градусов','Классический борщ по украинскому рецепту', 'Налейте в кастрюлю 2 литра воды, положите мясо. После закипания накройте кастрюлю крышкой и варите на медленном огне час. Пока варится бульон, вымойте свеклу, предварительно отваренную, морковь и лук. Свеклу и морковь натереть. Лук порезать. Затем на сковороде пожарить лук и морковь 5 минут, затем добавить к ним свеклу. Жарить еще 5 минут, затем добавить томатной пасты и еще 5 минут. Когда отварится мясо, выложите его и запустите в бульон нашинкованную капусту. Через 5-10 минут добавьте нарезанный соломкой картофель. Пока варится картофель, порежьте мясо и верните его в суп. Посолить, поперчить по вкусу. Добавить зажарку. Затем добавить лавровый лист и зелень. Варить еще 5 минут.')
INSERT INTO RecipeDetails(RecipeId,CookingTime,CookingTemperature,Description,Sequencing) VALUES (2,'10 минут', null,'Простейший вариант греческого салата','Нарезать огурцы, помидоры, перец, сыр Фета. Добавить растительного масла, соль и перец.')
INSERT INTO RecipeDetails(RecipeId,CookingTime,CookingTemperature,Description,Sequencing) VALUES(3, '1 час', '150 градусов','Как у бабушки','Отрежьте у хлеба корочку и замочите мякиш в молоке.В миске смешайте фарш, натёртый на мелкой тёрке чеснок, желтки, столовую ложку оливкового масла, перец и соль. Добавьте размоченный хлеб и хорошо всё перемешайте. Разогрейте сковороду и добавьте оставшееся оливковое масло. Сформируйте котлеты и жарьте на среднем огне до образования золотистой корочки.Добавьте воду и тушите 10 минут')
INSERT INTO RecipeDetails(RecipeId,CookingTime,CookingTemperature,Description,Sequencing) VALUES(4, '15 минут','150 градусов', null, 'Отбить куриные грудки. Посыпать солью и перцем. Жарить на растительном масле на предварительно разогретой сковороде по 2 минуты с каждой стороны')
INSERT INTO RecipeDetails(RecipeId,CookingTime,CookingTemperature,Description,Sequencing) VALUES(5, '5 минут',null, null, 'Нарезать огурцы, помидоры. Высыпать в тарелку, добавить немного масла, соли и перца.')
INSERT INTO RecipeDetails(RecipeId,CookingTime,CookingTemperature,Description,Sequencing) VALUES(6, '20 минут', '150 градусов', 'Сочные отбиные', 'Отбить свинину. Посыпат солью и перцем. Жарить на растительном масле на предварительно разогретой сковороде по 4 минуты с каждой стороны')
INSERT INTO RecipeDetails(RecipeId,CookingTime,CookingTemperature,Description,Sequencing) VALUES(7, '2-2.5 часа', '100 градусов', 'Очень вкусные русские щи', 'Мясо отварить в подсоленной воде (30-40 минут после закипания). Затем добавить в бульон нашинкованную соломкой капусту. Через 5 минут добавить картофель, нарезанный кубиками или брусочками. Варить еще 15 минут. Тем временем морковь натереть на крупной терке, лук измельчить, болгарский перец порезать полукольцами, а помидоры – дольками. Обжарить овощи в сковороде на растительном масле, добавив в конце жарки мелко порезанный чеснок и томатную пасту. Готовую зажарку переложить в кипящие щи, убавить огонь и варить суп ещё 5-7 минут. В конце варки добавить лавровый лист.')
INSERT INTO RecipeDetails(RecipeId,CookingTime,CookingTemperature,Description,Sequencing) VALUES(8, '5 минут', null, 'Нет ничего проще', 'Порезать огурцы, помидоры, перец. Выложить на тарелку. Посыпать солью')

INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,1,'2 литра')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,2,'Пару щепоток')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,3,'По вкусу')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,4,'2 шт.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,5,'По вкусу')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,6,'По вкусу')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,7,'300 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,8,'200 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,9,'100 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,10,'300 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,11,'3 шт.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,12,'2 ст.л.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,11,'10 мл.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (1,20,'500 гр.')

INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (2,2,'Пару щепоток')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (2,3,'По вкусу')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (2,5,'На глаз')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (2,27,'10 мл.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (2,16,'4 шт.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (2,17,'4 шт.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (2,18,'2 шт.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (2,23,'200 гр.')

INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (3,25,'100 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (3,26,'200 мл.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (3,22,'500 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (3,24,'500 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (3,14,'3 зубчика')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (3,15,'2 шт.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (3,27,'2 ст.л.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (3,1,'200 мл.')

INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (4,19,'1 кг.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (4,2,'Пару щепоток')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (4,3,'По вкусу')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (4,13,'10 мл.')

INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (5,16,'400 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (5,2,'Пару щепоток')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (5,17,'200 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (5,13,'10 мл.')

INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (6,21,'1 кг.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (6,2,'Пару щепоток')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (6,3,'По вкусу')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (6,13,'10 мл.')

INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,1,'2 литра')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,2,'Пару щепоток')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,3,'По вкусу')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,4,'2 шт.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,5,'По вкусу')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,6,'По вкусу')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,7,'300 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,8,'200 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,10,'2 ст.л.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,11,'2 шт.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,13,'10 мл.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,17,'150 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,18,'100 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (7,20,'500 гр.')

INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (8,2,'Пару щепоток')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (8,16,'400 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (8,17,'300 гр.')
INSERT INTO RecipeIngridient(RecipeId, IngridientId, Weight) VALUES (8,18,'200 гр.')

INSERT INTO UserRole(Name) VALUES ('Guest')
INSERT INTO UserRole(Name) VALUES ('Editor')
INSERT INTO UserRole(Name) VALUES ('Admin')

INSERT INTO Users(Login, Password, Email) VALUES ('Guest', 'guest', 'guest@gmail.com')
INSERT INTO Users(Login, Password, Email) VALUES ('Guest2', 'guest', 'guest2@gmail.com')
INSERT INTO Users(Login, Password, Email) VALUES ('Editor', 'editor', 'editor@gmail.com')
INSERT INTO Users(Login, Password, Email) VALUES ('Admin', 'admin', 'admin@gmail.com')

INSERT INTO UserUserRole(UserId, UserRoleId) VALUES (1,1)
INSERT INTO UserUserRole(UserId, UserRoleId) VALUES (2,1)
INSERT INTO UserUserRole(UserId, UserRoleId) VALUES (3,1)
INSERT INTO UserUserRole(UserId, UserRoleId) VALUES (3,2)
INSERT INTO UserUserRole(UserId, UserRoleId) VALUES (4,1)
INSERT INTO UserUserRole(UserId, UserRoleId) VALUES (4,2)
INSERT INTO UserUserRole(UserId, UserRoleId) VALUES (4,3)